name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install stable Rust
        run: rustup update stable && rustup default stable

      - name: Build
        run: cargo build --release --verbose

      - name: Test
        run: cargo test --verbose
